import type {CharacterVoice} from "speech/CharacterVoice";
import {SpeechSystemOption} from "speech/SpeechSystems";
import type {Message} from "../domain/Message";
import type {Tts} from "../domain/Tts";
import type {MediaFormat} from "../media";
import type {CreatorService} from "../system/CreatorService";

/** UI struct for a speech system with its name and all possible options */
class DisplaySpeechSystem {
  name: string;
  options: Array<CharacterVoice>;
  isFree: boolean;

  constructor(name: string, options: Array<CharacterVoice>, isFree: boolean) {
    this.name = name;
    if (options.length === 0) {
      throw Error("no options specified");
    }
    this.options = options;
    this.isFree = isFree;
  }
}

/**
 * Type representing the result of a request to generate speech from text.
 */
interface SpeechResult {
  filePath: () => string | undefined;
  tts: () => Tts | undefined;
}

/**
 * Represents a text to speech system.
 */
interface SpeechSystem extends CreatorService {

  /**
   * Generates spoken audio for message and returns relative filepath to audio from data base dir.
   * @param message
   * @param basename file base name
   */
  speak: (message: string, basename: string) => Promise<SpeechResult>;

  /**
   * Unique key for each option.
   */
  options: () => Array<SpeechSystemOption>;

  setCurrentOption: (value: string) => Promise<void>;

  /**
   * Command for inserting a speech of this duration or null if no such command exists
   */
  pauseCommand: (msDuration: number) => string | null;

  /**
   * Current voice for the speech system.
   */
  currentOption: () => SpeechSystemOption;
  display: DisplaySpeechSystem;

  /**
   * If the message is not generated by a user, return a new Message identical except with
   * the content stripped of any pause command for the SpeechSystem. If the message is
   * from the user, return the message unchanged.
   * @param m the message
   */
  removePauseCommands(m: Message): Message;

  /**
   * Provide the {@link MediaFormat} of the created audio.
   */
  outputFormat(): MediaFormat;
}

export {type SpeechSystem, type SpeechResult, DisplaySpeechSystem};
